### ISSUE TITLE
rds tx example

### ISSUE THREAD

**Issue by danybd** [bastibl/gr-rds#40]
Hello,
I tried the rds tx example with GNU 3.7, Windows 10 and a HackRF but it is not working. Do I have to configure something special? This is my console output:

gr-osmosdr c653754d (0.1.5git) gnuradio 3.7.12.0
built-in sink types: uhd hackrf bladerf redpitaya file
[INFO] [UHD] Win32; Microsoft Visual C++ version 14.0; Boost_106000; UHD_3.11.0.0-0-unknown
Using HackRF One with firmware 2017.02.1
PS set to "WDR 3"
nbuffers: 0
preparing 0
encoding 89.8
preparing 0
encoding 89.8
preparing 0
encoding 89.8
preparing 0
encoding 89.8
preparing group 1
preparing group 3
preparing group 3
preparing group 11
nbuffers: 26
INFO: Audio source arch: windows
UTraceback (most recent call last):
  File "C:\Users\bravo\Downloads\gr-rds-maint-3.7\apps\rds_tx.py", line 376, in <module>
    main()
  File "C:\Users\bravo\Downloads\gr-rds-maint-3.7\apps\rds_tx.py", line 370, in main
    tb = top_block_cls()
  File "C:\Users\bravo\Downloads\gr-rds-maint-3.7\apps\rds_tx.py", line 258, in __init__
    self.connect((self.audio_source_0, 1), (self.blocks_multiply_const_vxx_0_1, 0))
  File "C:\Program Files\GNURadio-3.7\lib\site-packages\gnuradio\gr\hier_block2.py", line 47, in wrapped
    func(self, src, src_port, dst, dst_port)
  File "C:\Program Files\GNURadio-3.7\lib\site-packages\gnuradio\gr\hier_block2.py", line 110, in connect
    self.primitive_connect(*args)
  File "C:\Program Files\GNURadio-3.7\lib\site-packages\gnuradio\gr\runtime_swig.py", line 5312, in primitive_connect
    return _runtime_swig.top_block_sptr_primitive_connect(self, *args)
ValueError: port number 1 exceeds max of 0
UUUUUUUUUUUUUUUUUUUUUUUUUUUUUU

**Comment by bastibl** [comment]
Looks like an issue with audio on Windows. I never used GNU Radio on Windows so I cannot help here. If you are mainly interested in RDS (and not in audio), just replace the audio source with a null source or similar.
