### ISSUE TITLE
Error reading in example flowgraphs

### ISSUE THREAD

**Issue by 777arc** [bastibl/gr-rds#57]
Anyone else getting KeyError: 'untyped' when opening the example flowgraphs?  I'm in 3.9.5, I tried opening maint-3.9, maint-3.10, and the one on master, but all errored out.  Would be cool if GR would tell me which block was causing the grc read error so I could investigate.
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gnuradio/grc/gui/Application.py", line 746, in _handle_action
    flow_graph_update()
  File "/usr/lib/python3/dist-packages/gnuradio/grc/gui/Application.py", line 110, in flow_graph_update
    fg.update()
  File "/usr/lib/python3/dist-packages/gnuradio/grc/gui/canvas/flowgraph.py", line 189, in update
    self.validate()
  File "/usr/lib/python3/dist-packages/gnuradio/grc/core/base.py", line 27, in validate
    child.validate()
  File "/usr/lib/python3/dist-packages/gnuradio/grc/core/Connection.py", line 101, in validate
    source_size = self.source_port.item_size
  File "/usr/lib/python3/dist-packages/gnuradio/grc/core/ports/port.py", line 79, in item_size
    return Constants.TYPE_TO_SIZEOF[self.dtype] * self.vlen
KeyError: 'untyped'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gnuradio/grc/gui/DrawingArea.py", line 203, in _handle_window_realize
    self._flow_graph.update()
  File "/usr/lib/python3/dist-packages/gnuradio/grc/gui/canvas/flowgraph.py", line 189, in update
    self.validate()
  File "/usr/lib/python3/dist-packages/gnuradio/grc/core/base.py", line 27, in validate
    child.validate()
  File "/usr/lib/python3/dist-packages/gnuradio/grc/core/Connection.py", line 101, in validate
    source_size = self.source_port.item_size
  File "/usr/lib/python3/dist-packages/gnuradio/grc/core/ports/port.py", line 79, in item_size
    return Constants.TYPE_TO_SIZEOF[self.dtype] * self.vlen
KeyError: 'untyped'
```

**Comment by 777arc** [comment]
I was able to open it just fine in 3.9.2 interestingly enough, not sure if my 3.9.5 install is screwed up or if something is actually broke

**Comment by 777arc** [comment]
mmm i think my playing around with newsched screwed it up
