### ISSUE TITLE
ImportError: libgnuradio-blocks.so.3.8.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by rapbando** [bastibl/gr-rds#67]
Installed gr-rds on kali rolling from repository and building from source and always  I get this error that gnuradio cannot open shared object. 

```
<<< Welcome to GNU Radio Companion 3.10.3.0 >>>

Block paths:
	/usr/share/gnuradio/grc/blocks
	/usr/local/share/gnuradio/grc/blocks

Loading: "/home/user/gr-rds-3.10/examples/rds_rx.grc"
>>> Done

Generating: '/home/user/gr-rds-3.10/examples/rds_rx.py'

Executing: /usr/bin/python3 -u /home/user/gr-rds-3.10/examples/rds_rx.py

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/osmosdr/__init__.py", line 17, in <module>
    from .osmosdr_python import *
ImportError: libgnuradio-blocks.so.3.8.1: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/gr-rds-3.10/examples/rds_rx.py", line 42, in <module>
    import osmosdr
  File "/usr/lib/python3/dist-packages/osmosdr/__init__.py", line 21, in <module>
    from .osmosdr_python import *
ImportError: libgnuradio-blocks.so.3.8.1: cannot open shared object file: No such file or directory

>>> Done (return code 1)
```

Also osmosdr is up to date:

```
gr-osmosdr/kali-rolling,now 0.2.3-6+b2 amd64 [installed]
  Gnuradio blocks from the OsmoSDR project

libgnuradio-osmosdr0.2.0/kali-rolling,now 0.2.3-6+b2 amd64 [installed]
  Gnuradio blocks from the OsmoSDR project - library

libosmosdr-dev/kali-rolling,now 0.1.8.effcaa7-7+b1 amd64 [installed]
  Software defined radio support for OsmoSDR hardware (development files)

libosmosdr0/kali-rolling,now 0.1.8.effcaa7-7+b1 amd64 [installed,automatic]
  Software defined radio support for OsmoSDR hardware (library)

osmo-sdr/kali-rolling,now 0.1.8.effcaa7-7+b1 amd64 [installed]
  Software defined radio support for OsmoSDR hardware (tools)
```

**Comment by bastibl** [comment]
This is an issue with your `osmosdr` installation. It looks like you have a GNU Radio 3.10 installation but a 3.8 installation of osmosdr. You can just open a Python shell and `import osmosdr`, it will probably fail in the same way, demonstrating that this is unrelated to gr-rds.
